### ISSUE TITLE
output context image

### ISSUE THREAD

**Issue by apatel726** [apatel726/HurricaneDissertation#34] opened 2020-12-08 05:10 UTC
![Image 12-7-20 at 9 16 PM](https://user-images.githubusercontent.com/62676972/101442648-fa65d080-38d8-11eb-80b5-e3ce9c2d4a0c.jpeg)

**Comment by hammad93** [comment] 2020-12-13 01:40
closing, duplicate of #33

**Closed by hammad93** 2020-12-13 01:40 UTC
